#!/bin/python
import struct
from lib.segment import Segment
from lib.rdt_client import *
import time  
class FRDT_Upload(FRDTClient):
    def __init__(self):
        super().__init__("File Reliable Data Transfer")
        self.parser.add_argument("-s", "--src",required=True,help="path to source file")
    
    def run(self):
        self.setup()
        if not os.path.exists(self.args.src):
            logger.error(f"El archivo {self.args.src} no existe.")
            return
        size= os.path.getsize(self.args.src)
        payload = struct.pack("!BQ", self.args.protocol, size) + self.args.name.encode()
        try:
            # Handshake
            self.rdt_sock.connect(const.OP_START_UPLOAD, payload)
            start_time = time.time()
            # envio los datos
            with open(self.args.src, "rb") as f:
                #el socket rdt se encarga de crear los paquetes
                self.rdt_sock.send(f.read())
            final_time = time.time()-start_time
            #estadisticas de tiempo y throughput   
            show_stats(final_time,size)
        except Exception as e:
            logger.error(f"Error en la subida: {e}")
        finally:
            self.rdt_sock.close()

if __name__ == "__main__":
    FRDT_Upload().run()